services:

  rabbit:
    restart: unless-stopped
    image: rabbitmq:3.9.29-management
    container_name: rabbit
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 4s
      timeout: 10s
      retries: 10
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - type: bind
        source: ./rabbit/rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./rabbit/rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - type: bind
        source: ./rabbit/rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_LISTENERS: EXTERNAL_SAME_HOST://:29092,INTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL_SAME_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL_SAME_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181" ]
      interval: 4s
      timeout: 10s
      retries: 10

  dtm:
    image: yedf/dtm
    restart: always
    healthcheck:
      test:  ["CMD", "curl", "-f", "http://localhost:36789"]
      interval: 4s
      timeout: 10s
      retries: 10
    ports:
      - 36790:36790 # grpc
      - 36789:36789 # ui

  currency:
    restart: unless-stopped
    build: ./currency
    ports:
      - 8083
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      - PORT=8083
      - NETWORK=tcp
      - COINGEKCO_URL=https://api.coingecko.com/api/v3/simple/price?ids=%s&vs_currencies=%s
      - COINAPI_URL=https://rest.coinapi.io/v1/exchangerate/%v/%v
      - COIN_API_KEY=FE1CB696-E794-4291-BECE-339379BA0726
      - KUNA_URL=https://api.kuna.io/v4/markets/public/tickers?pairs=%s_%s
      - RATE_CACHE_TIME=5000
      - AMQP_URL=amqp://guest:guest@rabbit:5672/default-vhost

  storage:
    restart: unless-stopped
    build: ./storage
    ports:
      - 8082
    environment:
      - STORAGE_PATH=./email/source/emails.csv
      - PORT=8082
      - NETWORK=tcp

  email:
    restart: unless-stopped
    build: ./email
    ports:
      - 8081
    environment:
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_SENDER=genesistesttask7@gmail.com
      - EMAIL_PASS=kvrkgmppacjpfngu
      - NETWORK=tcp
      - PORT=8081

  api:
    restart: unless-stopped
    depends_on:
      kafka:
        condition: service_healthy
      dtm:
        condition: service_started
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8080:8080
    environment:
      - EMAIL_SERVICE_PORT=8081
      - STORAGE_SERVICE_PORT=8082
      - CURRENCY_SERVICE_PORT=8083
      - EMAIL_NETWORK=email
      - CURRENCY_NETWORK=currency
      - STORAGE_NETWORK=storage
      - PORT=8080
      - KAFKA_ADDRESS=kafka:9092
      - DTM_ADDRESS=dtm:36790