name: Fundamental Pipeline
on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  resolve-modules:
    name: Resolve modules
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - id: set-matrix
        working-directory: ./services
        run: ../.github/workflows/script/resolve-modules.sh

  golangci:
    name: Linter
    runs-on: ubuntu-latest
    needs: resolve-modules
    strategy:
      matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.6.0
        with:
          version: v1.53
          working-directory: ./services/${{ matrix.workdir }}

  tests:
    name: Unit and Integration tests
    runs-on: ubuntu-latest
    needs: [ resolve-modules ]
    strategy:
      matrix: ${{ fromJson(needs.resolve-modules.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Run tests
        working-directory: ./services/${{ matrix.workdir }}
        run: go test -v ./...

  e2e-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    needs: [ tests ]
    steps:
      - uses: actions/checkout@v3
      - name: Rejuvenate services in Docker containers
        working-directory: ./services
        run: docker compose up -d
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Run E2E tests
        working-directory: ./test
        run: go test -v ./...
